version: '3'
services:
    dockerapp:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - redis
        networks: 
            - my_network
    redis:
        image: redis:3.2.0
        networks: 
            - my_network
networks:
    my_network:
        driver: bridge
